'use client';

import { CheckCircle2, Sparkles, Loader2 } from 'lucide-react';
import type {
  NewsSource,
  NewsProviderType,
  ExtractionPanelData,
  ExtractionTemplateVersion,
  TemplateGenerateResult,
  TemplateFieldName,
} from '../types';
import { WebsiteSourcePicker } from './WebsiteSourcePicker';

interface ExtractionDiagramPanelProps {
  isAdmin?: boolean;
  selectedTab: NewsProviderType | 'ALL';
  websiteSources: NewsSource[];
  selectedSourceId: string | null;
  onSelectSource: (id: string) => void;
  panel: ExtractionPanelData | null;
  isLoading: boolean;
  candidate: TemplateGenerateResult | null;
  actionState: 'idle' | 'generating' | 'saving' | 'activating' | 'rejecting';
  onGenerate: () => void;
  onSaveProposal: (
    template: TemplateGenerateResult['template'],
    generatedBy: string,
  ) => void;
}

const FIELD_ORDER: TemplateFieldName[] = [
  'title',
  'summary',
  'publishedAt',
  'url',
];

function formatDate(iso: string | null | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('en-US', { hour12: false });
}

function versionLabel(version: ExtractionTemplateVersion): string {
  return `v${version.version}`;
}

export function ExtractionDiagramPanel({
  isAdmin = false,
  selectedTab,
  websiteSources,
  selectedSourceId,
  onSelectSource,
  panel,
  isLoading,
  candidate,
  actionState,
  onGenerate,
  onSaveProposal,
}: ExtractionDiagramPanelProps) {
  const isNonWebsiteTab = selectedTab === 'RSS' || selectedTab === 'HTML';

  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
      <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 pb-3">
        <h3 className="text-sm font-bold text-slate-900">
          LLM-assisted Extraction
        </h3>
        <div className="flex items-center gap-2">
          <WebsiteSourcePicker
            sources={websiteSources}
            selectedSourceId={selectedSourceId}
            onSelect={onSelectSource}
          />
          {panel?.activeVersion && (
            <div className="flex items-center gap-1.5 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-0.5 text-xs font-semibold text-emerald-700">
              <span>Template: {versionLabel(panel.activeVersion)}</span>
              <CheckCircle2 className="size-3.5" />
            </div>
          )}
        </div>
      </div>

      {isNonWebsiteTab ? (
        <p className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50/50 p-4 text-center text-xs text-slate-400">
          Extraction Templates only apply to Website sources. Select the
          &quot;Website&quot; tab to view them.
        </p>
      ) : websiteSources.length === 0 ? (
        <p className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50/50 p-4 text-center text-xs text-slate-400">
          No Website Sources configured yet.
        </p>
      ) : isLoading ? (
        <p className="mt-4 text-center text-xs text-slate-400">Loading…</p>
      ) : !panel?.activeVersion ? (
        <p className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50/50 p-4 text-center text-xs text-slate-400">
          This source has no Extraction Template yet. Version 1 is generated and
          activated automatically on its first crawl.
        </p>
      ) : (
        <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
          <div className="flex flex-col rounded-xl border border-slate-200 bg-slate-50/50 p-3">
            <span className="text-xs font-bold text-slate-800">
              Item container
            </span>
            <div className="mt-2 rounded-lg border border-slate-200 bg-slate-900 p-2 font-mono text-[11px] text-emerald-300 overflow-x-auto">
              {panel.activeVersion.template.item}
            </div>
            <div className="mt-2.5 space-y-1 font-mono text-[10px] text-slate-600">
              {FIELD_ORDER.map((field) => {
                const locator = panel.activeVersion?.template.fields[field];
                return (
                  <div key={field} className="flex justify-between gap-2">
                    <span className="text-slate-500">{field}</span>
                    <span className="truncate text-blue-600">
                      {locator?.selector}
                      {locator?.attr ? ` [${locator.attr}]` : ''}
                    </span>
                  </div>
                );
              })}
            </div>
            <div className="mt-3 border-t border-slate-100 pt-1.5 text-[11px] font-bold text-emerald-600">
              Confidence: {panel.activeVersion.confidence.toFixed(2)}
            </div>
            <div className="text-[10px] text-slate-400">
              Generated by {panel.activeVersion.generatedBy} ·{' '}
              {formatDate(panel.activeVersion.activatedAt)}
            </div>
          </div>

          <div className="flex flex-col rounded-xl border border-slate-200 bg-slate-50/50 p-3">
            <span className="text-xs font-bold text-slate-800">Versions</span>
            <div className="mt-2 space-y-1.5">
              {panel.versionHistory.slice(0, 6).map((version) => (
                <div
                  key={version.id}
                  className={`flex items-center justify-between rounded-lg border px-2 py-1 text-[10px] font-medium ${
                    version.status === 'ACTIVE'
                      ? 'border-emerald-200 bg-emerald-50/60 text-emerald-900'
                      : 'border-slate-100 bg-slate-50 text-slate-600'
                  }`}
                >
                  <div>
                    <span className="font-bold">{versionLabel(version)}</span>{' '}
                    <span className="text-[9px] uppercase">
                      {version.status}
                    </span>
                    <p className="text-[9px] opacity-70">
                      {formatDate(version.createdAt)}
                    </p>
                  </div>
                </div>
              ))}
              {panel.versionHistory.length === 0 && (
                <p className="text-[10px] text-slate-400">
                  No version history yet.
                </p>
              )}
            </div>
          </div>

          {isAdmin && (
            <div className="flex flex-col rounded-xl border border-slate-200 bg-slate-50/50 p-3">
              <span className="text-xs font-bold text-slate-800">
                Generate a new version (trial)
              </span>
              <p className="mt-1 text-[10px] text-slate-500">
                Use the LLM to generate a candidate template from the live page,
                to review before saving it as a proposal.
              </p>

              {!candidate ? (
                <button
                  type="button"
                  onClick={onGenerate}
                  disabled={actionState === 'generating'}
                  className="mt-3 flex items-center justify-center gap-1.5 rounded-lg bg-blue-600 py-1.5 text-[11px] font-semibold text-white shadow-sm hover:bg-blue-700 disabled:opacity-50"
                >
                  {actionState === 'generating' ? (
                    <Loader2 className="size-3.5 animate-spin" />
                  ) : (
                    <Sparkles className="size-3.5" />
                  )}
                  {actionState === 'generating'
                    ? 'Generating…'
                    : 'Generate candidate template'}
                </button>
              ) : (
                <div className="mt-2 rounded-lg border border-slate-200 bg-white p-2 text-[10px]">
                  <p className="font-mono text-slate-700">
                    {candidate.template.item}
                  </p>
                  <p className="mt-1 text-slate-500">
                    Empty fields:{' '}
                    {(candidate.metrics.emptyFieldRate * 100).toFixed(1)}% ·
                    Malformed fields:{' '}
                    {(candidate.metrics.malformedFieldRate * 100).toFixed(1)}%
                  </p>
                  <button
                    type="button"
                    disabled={actionState === 'saving' || !panel.activeVersion}
                    onClick={() =>
                      onSaveProposal(candidate.template, candidate.generatedBy)
                    }
                    className="mt-2 w-full rounded-lg border border-blue-200 bg-blue-50 py-1 text-[10px] font-semibold text-blue-700 hover:bg-blue-100 disabled:opacity-50"
                  >
                    {actionState === 'saving'
                      ? 'Saving…'
                      : 'Save as proposal (PROPOSED)'}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
